language: groovy
jdk:
- oraclejdk8
before_install:
    - sudo apt-get update -q
    - sudo apt-get install graphviz
    
install: /bin/true
script:
- TERM=dumb gradle ascii --info --stacktrace    

    
