---
file: prob_developer.adoc
title: ProB Developer Handbook
authors:
  - Jens Bendisposto
  - Joy Clark
  - Michael Leuschel
content:
  - developer
  - appendix
---
file: prob_user_manual.adoc
title: ProB User Manual
authors:
  - Jens Bendisposto
  - Michael Leuschel
content:
  - user
  - model_examples
